### ISSUE TITLE
LOST ITAM TOKENS

### ISSUE THREAD

**Issue by reynadolfojr** [itamgames/itam-bridge-core#1]
I used ITAM Bridge to transfer my ITAM Tokens from Ethereum Network Metamask to Binance Smart Chain Metamask after the process ITAM Tokens are no longer on any Mainnet Wallet.

Etherscan Transaction Hash: 0xb0843c6cf3fee0ef25a414ea45dde865ac7b1cbef78f0bac2d0a642a1b4d6db0

Please fix the issue so that I could retrieve all my lost ITAM Tokens.

Thank you!

**Comment by changmyeong** [comment]
@reynadolfojr Sorry for the confusion. The Smart contract events were occasionally missing from node. Now it's resolved.
